// Plain-English descriptions for common WordPress plugins, keyed by slug -
// helps non-technical customers understand what's installed on their site
// without needing to look anything up. Curated list of widely-used plugins;
// intentionally returns null for anything unrecognized rather than guessing.
const PLUGIN_DESCRIPTIONS: Record<string, string> = {
	'akismet': 'Filters out spam comments and form submissions automatically.',
	'jetpack': 'Adds security, performance, and site management tools from Automattic.',
	'wordpress-seo': 'Helps optimize your pages and posts to rank better in search results.',
	'seo-by-rank-math': 'Helps optimize your pages and posts to rank better in search results.',
	'all-in-one-seo-pack': 'Helps optimize your pages and posts to rank better in search results.',
	'woocommerce': 'Turns your site into an online store for selling products.',
	'elementor': 'A drag-and-drop page builder for designing pages visually.',
	'contact-form-7': 'Adds customizable contact forms to your site.',
	'wpforms-lite': 'A drag-and-drop form builder for contact and other forms.',
	'wpforms': 'A drag-and-drop form builder for contact and other forms.',
	'gravityforms': 'A drag-and-drop form builder for contact and other forms.',
	'wordfence': 'Scans for malware and blocks malicious login attempts and traffic.',
	'ninjafirewall': 'A firewall that blocks malicious requests before they reach your site.',
	'wp-fail2ban': 'Blocks repeated failed login attempts to protect against brute-force attacks.',
	'simple-cloudflare-turnstile': 'Adds a CAPTCHA to forms to help block spam and bots.',
	'post-smtp': 'Improves email deliverability by sending mail through a proper mail service.',
	'better-wp-security': 'Hardens your site against common security threats.',
	'ithemes-security-pro': 'Hardens your site against common security threats.',
	'sucuri-scanner': 'Monitors your site for malware and security issues.',
	'updraftplus': 'Backs up your site and lets you restore it if something goes wrong.',
	'backwpup': 'Backs up your site and lets you restore it if something goes wrong.',
	'duplicator': 'Copies or migrates your site to another location.',
	'all-in-one-wp-migration': 'Copies or migrates your site to another location.',
	'wp-super-cache': 'Speeds up your site by serving cached versions of pages.',
	'w3-total-cache': 'Speeds up your site by caching pages and optimizing assets.',
	'wp-rocket': 'Speeds up your site by caching pages and optimizing assets.',
	'litespeed-cache': 'Speeds up your site by caching pages and optimizing assets.',
	'wp-fastest-cache': 'Speeds up your site by caching pages and optimizing assets.',
	'autoptimize': 'Speeds up your site by combining and compressing its files.',
	'wp-optimize': 'Cleans up and speeds up your site\u2019s database.',
	'smush': 'Compresses images to reduce their file size without losing quality.',
	'ewww-image-optimizer': 'Compresses images to reduce their file size without losing quality.',
	'really-simple-ssl': 'Keeps your site running securely over HTTPS.',
	'redirection': 'Manages URL redirects and tracks broken links (404s).',
	'advanced-custom-fields': 'Lets developers add custom content fields to pages and posts.',
	'advanced-custom-fields-pro': 'Lets developers add custom content fields to pages and posts.',
	'autodescription': 'Helps optimize your pages and posts to rank better in search results.',
	'classic-editor': 'Brings back the older WordPress writing/editing experience.',
	'tablepress': 'Adds and manages tables of data on your pages and posts.',
	'mailpoet': 'Sends newsletters and email campaigns to your subscribers.',
	'wp-mail-smtp': 'Improves email deliverability by sending mail through a proper mail service.',
	'google-site-kit': 'Connects your site to Google Analytics, Search Console, and other Google tools.',
	'ga-google-analytics': 'Connects your site to Google Analytics for traffic reporting.',
	'monsterinsights': 'Shows Google Analytics data inside your WordPress dashboard.',
	'yith-woocommerce-wishlist': 'Adds a wishlist feature to your online store.',
	'polylang': 'Lets you run your site in multiple languages.',
	'sitepress-multilingual-cms': 'Lets you run your site in multiple languages.',
	'revslider': 'Adds animated image and content sliders to your pages.',
	'slider-revolution': 'Adds animated image and content sliders to your pages.',
	'envira-gallery-lite': 'Adds photo galleries to your pages and posts.',
	'nextgen-gallery': 'Adds photo galleries to your pages and posts.',
	'bbpress': 'Adds discussion forums to your site.',
	'buddypress': 'Adds social network features like member profiles and groups.',
	'give': 'Lets visitors make donations directly on your site.',
	'easy-digital-downloads': 'Sells digital products like ebooks or software from your site.',
	'memberpress': 'Restricts content and manages paid memberships.',
	'learndash': 'Turns your site into an online course platform.',
	'custom-post-type-ui': 'Lets developers create custom content types beyond posts and pages.',
	'duplicate-post': 'Lets you quickly duplicate existing pages or posts.',
	'wpml': 'Lets you run your site in multiple languages.',
	'query-monitor': 'A developer debugging tool for diagnosing performance issues.',
	'broken-link-checker': 'Scans your site for broken links and missing images.',
	'cookie-notice': 'Shows a cookie consent banner to comply with privacy laws.',
	'gdpr-cookie-consent': 'Shows a cookie consent banner to comply with privacy laws.',
	'loco-translate': 'Lets you translate the text used by your theme and plugins.',
	'manageWP-worker': 'Allows your site to be managed remotely from a central dashboard.',
	'andybz-monitor-connector': 'Reports your site\u2019s health and activity to CauseTrail.'
};

export function getPluginDescription(slug: string): string | null {
	return PLUGIN_DESCRIPTIONS[slug] ?? null;
}
